### PR TITLE
Updated  GeoNode ansible role to work with current GeoNode master

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by t-book** [comment]
@kalxas You’re starting the celery service
https://github.com/GeoNode/ansible-geonode/blob/master/tasks/celery.yml#L13
But I cannot see that ASYNC_SIGNALS is set  to true. (So Signals might still run synchronous?)

`ASYNC_SIGNALS = ast.literal_eval(os.environ.get('ASYNC_SIGNALS', 'false'))
`(False by default)
https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1331

If it’s not somewhere set maybe it could be added to  geonode-project settings file or as ENV var?

**Comment by kalxas** [comment]
@t-book I have not done any changes to the celery task

**Comment by t-book** [comment]
@kalaxas With current settings it's enabled but not used. (IMHO this is not relevant for this PR. We can change it in a next step) Anyways, I could not save maps , I think the local_settings needs to be updated relating geoserver location. Have you tested creating a new map?

**Comment by kalxas** [comment]
Thanks for the feedback @t-book 
I am working on it.
Shall we merge this one and open a new PR?

**Comment by kalxas** [comment]
Thanks @t-book for the review.
@afabiani @francbartoli @ingenieroariel @simod can you please review/merge?

**Comment by ingenieroariel** [comment]
I have been working on a VM created with this ansible role these past few weeks and all looks good to me. Merging.

**Comment by kalxas** [comment]
Thanks @ingenieroariel

**Pull request merged**
